version: 2
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context: github
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: setup git
          command: |
            git config --global credential.helper 'cache --timeout=120'
            git config --global user.email "joway.w@gmail.com"
            git config --global user.name "Joway.CI"
      - run:
          name: install
          command: |
            npm install
      - run:
          name: build site
          command: |
            npm run build
      - deploy:
          name: push newest site
          command: |
            export msg=$(git log --pretty=format:%s -1)
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if [ -n "$(git status --porcelain)" ]; then
                mv ./dist /dist
                git stash
                git checkout gh-pages
                find ./ -not -name '.git' -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf --
                mv /dist ./
                git add .
                git commit --allow-empty -m "$msg"
                git push -q https://${GITHUB_TOKEN}@github.com/joway/jallery.git gh-pages --force
              else
                echo "no changes";
              fi
            fi
