version: 2
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context: github
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: setup git
          command: |
            git config --global credential.helper 'cache --timeout=120'
            git config --global user.email "joway.w@gmail.com"
            git config --global user.name "Joway.CI"
            git checkout -b gh-pages
      - run:
          name: install
          command: |
            npm install
      - run:
          name: build site
          command: |
            npm run build
      - deploy:
          name: push newest site
          command: |
            if [ -n "$(git status --porcelain)" ]; then
              git add .
              git commit --allow-empty -m 'ci-build: build static sites'
              git push -q https://${GITHUB_TOKEN}@github.com/joway/jallery.git gh-pages --force
            else
              echo "no changes";
            fi
